"""Add is_tenant column to Property

Revision ID: 100f30361330
Revises: 93b4b37b11fe
Create Date: 2025-02-17 17:06:00.358915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100f30361330'
down_revision = '93b4b37b11fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_tenant', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('is_tenant')

    # ### end Alembic commands ###
